# Generated by Django 5.2.7 on 2025-10-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='media/qrcodes/'),
        ),
    ]
