# Generated by Django 5.2.7 on 2025-10-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdine', '0002_alter_table_qr_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isBlocked',
            new_name='is_blocked',
        ),
        migrations.AlterField(
            model_name='table',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
