# Generated by Django 5.2.7 on 2025-11-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdine', '0004_user_password_reset_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='customizable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='spice_level',
            field=models.IntegerField(choices=[(0, 'No Spice'), (1, 'Mild'), (2, 'Medium'), (3, 'Hot')], default=0),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='type',
            field=models.CharField(choices=[('veg', 'Veg'), ('non-veg', 'Non-Veg')], default='veg', max_length=20),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('starter', 'Starter'), ('main', 'Main Course'), ('dessert', 'Dessert'), ('drink', 'Drink')], max_length=20),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
