# Generated by Django 5.2.7 on 2025-11-02 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdine', '0005_menuitem_customizable_menuitem_spice_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='special_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='smartdine.table'),
        ),
    ]
