# Generated by Django 5.2.7 on 2025-11-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdine', '0007_orderitem_subtotal_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='preparation_time',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_time',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
