# Generated by Django 5.2.7 on 2025-11-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdine', '0008_menuitem_preparation_time_order_estimated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='estimated_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
