# Generated by Django 5.2.7 on 2025-11-04 05:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdine', '0010_rename_comment_feedback_comments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('3.99'), max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('fruit', 'Fruit'), ('green', 'Green'), ('sweetener', 'Sweetener'), ('extra', 'Extra'), ('spice', 'Spice'), ('citrus', 'Citrus')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='CustomDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartdine.base')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_dishes', to='smartdine.table')),
            ],
        ),
        migrations.CreateModel(
            name='CustomDishIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('custom_dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_ingredients', to='smartdine.customdish')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartdine.ingredient')),
            ],
            options={
                'unique_together': {('custom_dish', 'ingredient')},
            },
        ),
    ]
