# Generated by Django 5.2.7 on 2025-11-04 05:20

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdine', '0011_base_ingredient_customdish_customdishingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customdish',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='customdish',
            name='table',
        ),
        migrations.RemoveField(
            model_name='customdish',
            name='total_price',
        ),
        migrations.AddField(
            model_name='customdish',
            name='is_custom',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customdish',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.99'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='customdish',
            name='base',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='smartdine.base'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customdish',
            name='name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
