# Generated by Django 5.2.7 on 2025-11-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdine', '0012_remove_customdish_notes_remove_customdish_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='base',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
