# Generated by Django 5.2.7 on 2025-11-04 05:50

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdine', '0013_base_description_alter_base_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customdish',
            name='is_custom',
        ),
        migrations.RemoveField(
            model_name='customdish',
            name='price',
        ),
        migrations.AddField(
            model_name='customdish',
            name='special_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customdish',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='customdish',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartdine.base'),
        ),
        migrations.AlterField(
            model_name='customdish',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
