# Generated by Django 5.2.7 on 2025-11-04 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdine', '0014_remove_customdish_is_custom_remove_customdish_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='custom_dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smartdine.customdish'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smartdine.menuitem'),
        ),
    ]
