# Generated by Django 5.2.7 on 2025-11-04 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdine', '0015_cartitem_custom_dish_cartitem_is_custom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='custom_dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smartdine.customdish'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smartdine.menuitem'),
        ),
    ]
