# Generated by Django 5.2.7 on 2025-11-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdine', '0016_orderitem_custom_dish_alter_orderitem_menu_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdish',
            name='preparation_time',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
