# Generated by Django 5.2.7 on 2025-11-04 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdine', '0017_customdish_preparation_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customdish',
            name='preparation_time',
        ),
        migrations.AddField(
            model_name='customdish',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_dishes', to='smartdine.table'),
        ),
    ]
