# Generated by Django 5.2.7 on 2025-11-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdine', '0018_remove_customdish_preparation_time_customdish_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdish',
            name='preparation_time',
            field=models.PositiveIntegerField(default=0, help_text='Time in minutes'),
        ),
    ]
