# Generated by Django 5.2.7 on 2025-11-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdine', '0019_customdish_preparation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdish',
            name='sold_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
