# Generated by Django 5.2.7 on 2025-11-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdine', '0020_customdish_sold_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdish',
            name='image_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='customdish',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
