# Generated by Django 5.2.7 on 2025-11-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdine', '0021_customdish_image_status_customdish_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Available quantity for this item'),
        ),
    ]
