# Generated by Django 5.2.7 on 2025-11-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdine', '0022_menuitem_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiterrequest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waiterrequest',
            name='type',
            field=models.CharField(choices=[('need water', 'Need Water'), ('need bill', 'Need Bill'), ('clean table', 'Clean Table'), ('general', 'General Request')], max_length=20),
        ),
    ]
