# Generated by Django 5.2.7 on 2025-11-06 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdine', '0023_waiterrequest_description_alter_waiterrequest_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveIntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArchivedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveIntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArchivedWaiterRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveIntegerField()),
                ('request_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArchivedCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_custom', models.BooleanField(default=False)),
                ('archived_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='smartdine.archivedcart')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivedOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_custom', models.BooleanField(default=False)),
                ('archived_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='smartdine.archivedorder')),
            ],
        ),
        migrations.CreateModel(
            name='TableHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='smartdine.table')),
            ],
        ),
    ]
