# Generated by Django 5.2.7 on 2025-11-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdine', '0024_archivedcart_archivedorder_archivedwaiterrequest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedcartitem',
            name='archived_cart',
        ),
        migrations.RemoveField(
            model_name='archivedorderitem',
            name='archived_order',
        ),
        migrations.DeleteModel(
            name='ArchivedWaiterRequest',
        ),
        migrations.AddField(
            model_name='tablehistory',
            name='snapshot',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='tablehistory',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied')], max_length=20),
        ),
        migrations.DeleteModel(
            name='ArchivedCart',
        ),
        migrations.DeleteModel(
            name='ArchivedCartItem',
        ),
        migrations.DeleteModel(
            name='ArchivedOrder',
        ),
        migrations.DeleteModel(
            name='ArchivedOrderItem',
        ),
    ]
