# Generated by Django 5.2.8 on 2025-11-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdine', '0025_remove_archivedcartitem_archived_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='started_preparing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
