# Generated by Django 5.2.8 on 2025-11-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdine', '0026_order_started_preparing_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='min_stock',
            field=models.PositiveIntegerField(default=5, help_text='Minimum stock before triggering low stock alert'),
        ),
    ]
