# Generated by Django 5.2.8 on 2025-11-11 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdine', '0027_menuitem_min_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='chef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_handled', to=settings.AUTH_USER_MODEL),
        ),
    ]
