# Generated by Django 5.2.8 on 2025-11-11 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdine', '0028_order_chef'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='chef',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'kitchen'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_as_chef', to=settings.AUTH_USER_MODEL),
        ),
    ]
