# Generated by Django 5.2.8 on 2025-11-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdine', '0029_alter_order_chef'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
