# Generated by Django 5.2.8 on 2025-11-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdine', '0030_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='orders_completed',
            field=models.IntegerField(default=0),
        ),
    ]
