# Generated by Django 5.2.8 on 2025-11-12 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdine', '0031_user_orders_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='waiter',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'waiter'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_as_waiter', to=settings.AUTH_USER_MODEL),
        ),
    ]
