# Generated by Django 5.2.8 on 2025-11-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdine', '0033_remove_user_points_cart_is_active_cartitem_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiterrequest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
