# Generated by Django 5.2.8 on 2025-11-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdine', '0036_chatsession_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='session_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
