# Generated by Django 5.2.8 on 2025-11-17 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdine', '0037_table_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='session_id',
        ),
        migrations.AddField(
            model_name='table',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='smartdine.chatsession'),
        ),
    ]
